plugins {
    id 'java'
    
}

repositories {
    // Используем корпоративный репозиторий (Nexus/Artifactory)
    maven {
        url 'https://nexus.sovcombank.group/repository/maven-public/'
       credentials {
            username = System.getenv('NEXUS_USERNAME') ?: 'anonymous'
            password = System.getenv('NEXUS_PASSWORD') ?: ''
       }
   }
    // Резервный репозиторий — только если основной недоступен
    mavenCentral()
}

dependencies {implementation("org.testng:testng:7.12.0")
              implementation("org.seleniumhq.selenium:selenium-java:4.41.0")
              implementation("org.slf4j:slf4j-simple:2.0.13")

}
test {
    useTestNG()
    testLogging {
        events "passed", "skipped", "failed"
    }
}